version: '3.9'
services:
  web:
    container_name: cool_site_web
    image: 'node:10-buster'
    user: 'node'
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      - ./web:/home/node/app
    ports:
      - '3000:3000'
    command: >
        bash -c "npm install
        && npm start"
    networks:
      - backend
    restart: always
  api:
    container_name: cool_site_api
    image: 'node:10-buster'
    user: 'node'
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      - ./api:/home/node/app
    expose:
      - '3001'
    command: >
        bash -c "npm install
        && npm start"
    depends_on:
      - db
    networks:
      - backend
    restart: always
  mail:
    container_name: cool_site_mail
    image: 'node:10-buster'
    user: 'node'
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    volumes:
      - ./mail:/home/node/app
    expose:
      - '3002'
    command: >
        bash -c "npm install
        && npm start"
    networks:
      - backend
    restart: always
  db:
    container_name: cool_site_db
    image: mysql:8.0.23
    expose:
      - '3306'
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: web2021_cool_site
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
    restart: always

volumes:
  db-data:
    driver: local

networks:
  backend:
    driver: bridge